---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: dailypay-staging-helm-release
  namespace: staging
  annotations:
    filter.fluxcd.io/chart-image: glob:staging-*
    fluxcd.io/automated: 'true'
spec:
  releaseName: dailypay-staging
  chart:
    git: git@github.com:dailypay/dailypay
    path: charts/dailypay
    ref: feature/helm-chart
    version: 0.1.1
  values:
    image:
      repository: 974673539992.dkr.ecr.us-east-1.amazonaws.com/dailypay
      tag: staging-24654
    web:
      create: true
      replicaCount: 2
      env:
      - name: RAILS_ENV
        value: staging
      service:
        type: ClusterIP
        port: 80
    worker:
      create: false
      replicaCount: 2
      env:
      - name: RAILS_ENV
        value: staging
    ingress:
      enabled: true
      annotations: {kubernetes.io/ingress.class: nginx, cert-manager.io/cluster-issuer: letsencrypt-production}
      hosts:
      - host: www.dailypaystaging.com
        paths: ['/']
      tls:
      - secretName: dailypaystaging-tls
        hosts:
        - "*.dailypaystaging.com"
